repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        entry: dotnet format --verify-no-changes
        language: system
        types: [csharp]
      - id: dotnet-lint
        name: dotnet build lint
        entry: dotnet build -warnaserror
        language: system
        types: [csharp]
