repos:
  - repo: local
    hooks:
      - id: csharpier
        name: Run CSharpier on C# files
        entry: csharpier format .
        language: system
        types:
          - c#
        description: CSharpier is an opinionated C# formatter inspired by Prettier.
