#!/bin/bash

CS_PROJ_FILE = "mggj.csproj"

set -e

dotnet format "$CS_PROJ_FILE" --verify-no-changes

if [[ $? -ne 0 ]]; then
    echo "Failed Formatting"
    exit 1
fi

dotnet build "$CS_PROJ_FILE" --no-restore

if [[ $? -ne 0 ]]; then
    echo "Failed Formatting"
    exit 1
fi

exit 0
